/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_mc_softphone_media_alsa_AudioDriverAlsa */

#ifndef _Included_com_sun_mc_softphone_media_alsa_AudioDriverAlsa
#define _Included_com_sun_mc_softphone_media_alsa_AudioDriverAlsa
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sun_mc_softphone_media_alsa_AudioDriverAlsa
 * Method:    nGetInputDevices
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_sun_mc_softphone_media_alsa_AudioDriverAlsa_nGetInputDevices
  (JNIEnv *, jobject);

/*
 * Class:     com_sun_mc_softphone_media_alsa_AudioDriverAlsa
 * Method:    nGetOutputDevices
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_sun_mc_softphone_media_alsa_AudioDriverAlsa_nGetOutputDevices
  (JNIEnv *, jobject);

/*
 * Class:     com_sun_mc_softphone_media_alsa_AudioDriverAlsa
 * Method:    nInitializeMicrophone
 * Signature: (Ljava/lang/String;III)I
 */
JNIEXPORT jint JNICALL Java_com_sun_mc_softphone_media_alsa_AudioDriverAlsa_nInitializeMicrophone
  (JNIEnv *, jobject, jstring, jint, jint, jint);

/*
 * Class:     com_sun_mc_softphone_media_alsa_AudioDriverAlsa
 * Method:    nInitializeSpeaker
 * Signature: (Ljava/lang/String;III)I
 */
JNIEXPORT jint JNICALL Java_com_sun_mc_softphone_media_alsa_AudioDriverAlsa_nInitializeSpeaker
  (JNIEnv *, jobject, jstring, jint, jint, jint);

/*
 * Class:     com_sun_mc_softphone_media_alsa_AudioDriverAlsa
 * Method:    nStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sun_mc_softphone_media_alsa_AudioDriverAlsa_nStop
  (JNIEnv *, jobject);

/*
 * Class:     com_sun_mc_softphone_media_alsa_AudioDriverAlsa
 * Method:    nWriteSpeaker
 * Signature: ([SI)I
 */
JNIEXPORT jint JNICALL Java_com_sun_mc_softphone_media_alsa_AudioDriverAlsa_nWriteSpeaker
  (JNIEnv *, jobject, jshortArray, jint);

/*
 * Class:     com_sun_mc_softphone_media_alsa_AudioDriverAlsa
 * Method:    nReadMic
 * Signature: ([SI)I
 */
JNIEXPORT jint JNICALL Java_com_sun_mc_softphone_media_alsa_AudioDriverAlsa_nReadMic
  (JNIEnv *, jobject, jshortArray, jint);

/*
 * Class:     com_sun_mc_softphone_media_alsa_AudioDriverAlsa
 * Method:    nFlushMicrophone
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sun_mc_softphone_media_alsa_AudioDriverAlsa_nFlushMicrophone
  (JNIEnv *, jobject);

/*
 * Class:     com_sun_mc_softphone_media_alsa_AudioDriverAlsa
 * Method:    nFlushSpeaker
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sun_mc_softphone_media_alsa_AudioDriverAlsa_nFlushSpeaker
  (JNIEnv *, jobject);

/*
 * Class:     com_sun_mc_softphone_media_alsa_AudioDriverAlsa
 * Method:    nMicrophoneAvailable
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sun_mc_softphone_media_alsa_AudioDriverAlsa_nMicrophoneAvailable
  (JNIEnv *, jobject);

/*
 * Class:     com_sun_mc_softphone_media_alsa_AudioDriverAlsa
 * Method:    nSpeakerAvailable
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sun_mc_softphone_media_alsa_AudioDriverAlsa_nSpeakerAvailable
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
