/*
 * Copyright 2007 Sun Microsystems, Inc.
 *
 * This file is part of jVoiceBridge.
 *
 * jVoiceBridge is free software: you can redistribute it and/or modify 
 * it under the terms of the GNU General Public License version 2 as 
 * published by the Free Software Foundation and distributed hereunder 
 * to you.
 *
 * jVoiceBridge is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Sun designates this particular file as subject to the "Classpath"
 * exception as provided by Sun in the License file that accompanied this 
 * code. 
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_voip_util_hrtimer_NativeHighResTimer */

#ifndef _Included_com_sun_voip_util_hrtimer_NativeHighResTimer
#define _Included_com_sun_voip_util_hrtimer_NativeHighResTimer
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: logger */
/* Inaccessible static: class_00024com_00024sun_00024voip_00024util_00024hrtimer_00024NativeHighResTimer */
/*
 * Class:     com_sun_voip_util_hrtimer_NativeHighResTimer
 * Method:    nInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sun_voip_util_hrtimer_NativeHighResTimer_nInit
  (JNIEnv *, jobject);

/*
 * Class:     com_sun_voip_util_hrtimer_NativeHighResTimer
 * Method:    nSleep
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_sun_voip_util_hrtimer_NativeHighResTimer_nSleep
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_sun_voip_util_hrtimer_NativeHighResTimer
 * Method:    nArm
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_sun_voip_util_hrtimer_NativeHighResTimer_nArm
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_sun_voip_util_hrtimer_NativeHighResTimer
 * Method:    nDisarm
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sun_voip_util_hrtimer_NativeHighResTimer_nDisarm
  (JNIEnv *, jobject);

/*
 * Class:     com_sun_voip_util_hrtimer_NativeHighResTimer
 * Method:    nTick
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sun_voip_util_hrtimer_NativeHighResTimer_nTick
  (JNIEnv *, jobject);

/*
 * Class:     com_sun_voip_util_hrtimer_NativeHighResTimer
 * Method:    nCleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sun_voip_util_hrtimer_NativeHighResTimer_nCleanup
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
