/*
 * Copyright 2007 Sun Microsystems, Inc.
 *
 * This file is part of jVoiceBridge.
 *
 * jVoiceBridge is free software: you can redistribute it and/or modify 
 * it under the terms of the GNU General Public License version 2 as 
 * published by the Free Software Foundation and distributed hereunder 
 * to you.
 *
 * jVoiceBridge is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Sun designates this particular file as subject to the "Classpath"
 * exception as provided by Sun in the License file that accompanied this 
 * code. 
 */

package bridgemonitor;

/**
 *
 * @author  jp
 */
public class BridgeMonitorUI extends javax.swing.JFrame {
    
    private BridgeStatusPanel bsp;

    public static void main(String[] args) {
	new BridgeMonitorUI();
    }

    /** Creates new form BridgeMonitorUI */

    public BridgeMonitorUI() {
        this(null, 0, 0, true);
    }

    public BridgeMonitorUI(int x, int y) {
        this(null, x, y, false);
    }

    public BridgeMonitorUI(String bridgeToMonitor, int x, int y) {
        this(bridgeToMonitor, x, y, false);
    }

    public BridgeMonitorUI(String bridgeToMonitor, int x, int y, 
	    boolean exitOnClose) {

        initComponents();

        //callTable.setVisible(true);

        setLocation(x, y);

	if (exitOnClose) {
            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
	} else {
            setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
	}

        setVisible(true);

	if (bridgeToMonitor != null) {
	    bridgeStatusPanel1.getBridgeTextField().setText(bridgeToMonitor
	        + ":5060:6666");
	} else {
	    bridgeStatusPanel1.getBridgeTextField().setText(
		"localhost:5060:6666");
	}

	bridgeStatusPanel1.setUI(this);
	bridgeStatusPanel2.setUI(this);
	bridgeStatusPanel3.setUI(this);
    }
    
    public void setCallTableOwner(BridgeStatusPanel bsp) {
	this.bsp = bsp;
    }

    public javax.swing.JTable getCallTable() {
	return callTable;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        rightPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        callTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        bridgeStatusPanel1 = new bridgemonitor.BridgeStatusPanel();
        bridgeStatusPanel2 = new bridgemonitor.BridgeStatusPanel();
        bridgeStatusPanel3 = new bridgemonitor.BridgeStatusPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bridge Monitor");
        setFont(new java.awt.Font("aakar", 1, 12));

        jSplitPane1.setDividerLocation(650);

        callTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Calls"
            }
        ));
        callTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                callTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(callTable);

        org.jdesktop.layout.GroupLayout rightPanelLayout = new org.jdesktop.layout.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                .addContainerGap())
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane1.setRightComponent(rightPanel);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(bridgeStatusPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 164, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(bridgeStatusPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(bridgeStatusPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(bridgeStatusPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(bridgeStatusPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(bridgeStatusPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(73, 73, 73))
        );

        jScrollPane2.setViewportView(jPanel1);

        jSplitPane1.setLeftComponent(jScrollPane2);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void callTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_callTableMouseClicked
    if (bsp == null) {
	return;
    }

    bsp.callTableMouseClicked(evt);
}//GEN-LAST:event_callTableMouseClicked
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private bridgemonitor.BridgeStatusPanel bridgeStatusPanel1;
    private bridgemonitor.BridgeStatusPanel bridgeStatusPanel2;
    private bridgemonitor.BridgeStatusPanel bridgeStatusPanel3;
    private javax.swing.JTable callTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel rightPanel;
    // End of variables declaration//GEN-END:variables
    
}
